language: cpp
dist: bionic
sudo: false

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - cmake
            - gcc-10
            - g++-10
      env: COMPILER=g++-10
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-10
          packages:
            - cmake
            - clang-10
      env: COMPILER=clang++-10

branches:
    only:
        - master

before_script:
  - export CC=$COMPILER
  - export CXX=$COMPILER

script:
  - cmake CMakeLists.txt -DGRAPHTHEWY_BUILD_TESTS=ON
  - make
  - ctest -C Debug
