language: cpp
dist: bionic
sudo: true

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - cmake
            - gcc-10
            - g++-10
            - criterion
            - wget
      env: COMPILER=g++-10
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-10
          packages:
            - cmake
            - clang-10
            - criterion
            - wget
      env: COMPILER=clang++-10

branches:
    only:
        - master

before_script:
  - export CC=$COMPILER
  - export CXX=$COMPILER
  - wget ttps://github.com/Snaipe/Criterion/releases/download/v2.3.3/criterion-v2.3.3.tar.bz2 && tar xaf criterion-v2.3.3.tar.bz2 && cd criterion-v2.3.3.tar.bz2 && cmake CMakeLists.txt && make && sudo make install && ldconfig


script:
  - cmake CMakeLists.txt -DGRAPHTHEWY_BUILD_TESTS=ON
  - make
  - ctest -C Debug
